#!/bin/bash

set -ex

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/MikeMcQuaid/strap/bd8c230a20c4f674efaacc9c250e1328092f1258/bin/strap.sh)"

# link .ssh from icloud
if [ -e /Users/$USER/.ssh ]; then
    echo "ssh config already symlinked"
else
    ln -s "/Users/$USER/Library/Mobile Documents/com~apple~CloudDocs/dev/.ssh" "/Users/$USER/.ssh"
fi;

brew install chezmoi
chezmoi init vladserkoff
chezmoi apply
